import Head from 'next/head';

import Landing from './components/Landing';
import styles from '../styles/LandingPage.module.css'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>  <main className="relative h-[200vh] bg-[#0E1129]"> <div className="flex items-center justify-center h-screen bg-[#0E1129]">
        <Landing />
      </div></main>
    </>
  );
}